USE tienda_videojuegos;

SELECT * FROM CATEGORIA;

SELECT * FROM VIDEOJUEGO;

SELECT * FROM CLASIFICACION_EDAD;

SELECT * FROM COMPRA;

SELECT * FROM COMENTARIO;

SELECT * FROM USUARIO;

SELECT * FROM MOVIMIENTO_SALDO;

SELECT * FROM BIBLIOTECA_JUEGO;

SELECT * FROM EMPRESA;

SELECT * FROM GRUPO_FAMILIAR;

SELECT * FROM MIEMBRO_GRUPO;

SELECT * FROM USUARIO_EMPRESA;

SELECT * FROM EMPRESA;
